
require 'open-uri'

Like.delete_all
Review.delete_all
CartItem.delete_all
User.delete_all
Product.delete_all

Faker::Name.unique.clear
demouser = User.create(username: "DemoUser", password: 'password')
user1 = User.create(username: "user1", password: 'password')
user2 = User.create(username: Faker::Name.unique.name, password: 'password')
user3 = User.create(username: Faker::Name.unique.name, password: 'password')
user4 = User.create(username: Faker::Name.unique.name, password: 'password')
user5 = User.create(username: Faker::Name.unique.name, password: 'password')
user6 = User.create(username: Faker::Name.unique.name, password: 'password')
user7 = User.create(username: Faker::Name.unique.name, password: 'password')
user8 = User.create(username: Faker::Name.unique.name, password: 'password')
user9 = User.create(username: Faker::Name.unique.name, password: 'password')

new1 = Product.create(name: "Marianna Puff-Sleeve Midi Dress in Plaid", gender: "womens", category: "new", price: 135.00, description: "Made of breezy cotton, this plaid midi dress has lots of details to love: a faux-wrap bodice, raglan puff sleeves and a roomy skirt with delicate pintucks. A pretty, no-fuss style.")
new1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new1_1.jpg"), filename: "new1_1.jpg")
new1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new1_2.jpg"), filename: "new1_2.jpg")
new2 = Product.create(name: "The Perfect Vintage Wide-Leg Crop Jean in Bosworth Wash: Raw-Hem Edition", gender: "womens", category: "new", price: 135.00, description: "The cut: A recent addition to our Perfect Vintage fam, these cropped jeans combine the high fitted waist you love with slouchy wide legs. The fabric: Blended with light and airy hemp, this premium eco-friendly denim has an old-school look and a touch of stretch for a broken-in feel.")
new2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new2_1.jpg"), filename: "new2_1.jpg")
new2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new2_2.jpg"), filename: "new2_2.jpg")
new3 = Product.create(name: "Relaxed Fatigue Shorts", gender: "womens", category: "new", price: 88.00, description: "The cut: redesigned for a cooler, slouchier vibe, these army surplus-inspired shorts sit low on the hips for a laid-back look and are long enough to cuff. The fabric: woven from cotton grown in the United States, it's soft and textural with a perfectly broken-in feel.")
new3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new3_1.jpg"), filename: "new3_1.jpg")
new3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new3_2.jpg"), filename: "new3_2.jpg")
new4 = Product.create(name: "Linen-Blend Tie-Back Wide-Leg Jumpsuit", gender: "womens", category: "new", price: 135.00, description: "Cut from a drapey (and eco-friendly) linen blend, this jumpsuit has an easy high waist, exaggerated wiiiiiiiide legs and thin straps that tie in back. The best part? You can dress it up or down (wear it to the office with a blazer or layer it over a tee for a weekend girls picnic).")
new4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new4_1.jpg"), filename: "new4_1.jpg")
new4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new4_2.jpg"), filename: "new4_2.jpg")
new5 = Product.create(name: "Floral Check Jacquard Knit Camp Shirt", gender: "womens", category: "new", price: 75.00, description: "A vacation no-brainer (cuz it doubles as a cover-up), this button-up camp shirt comes in stretchy jacquard with bold knit-right-in flowers. Just don't forget to pack the matching shorts (!).")
new5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new5_1.jpg"), filename: "new5_1.jpg")
new5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new5_2.jpg"), filename: "new5_2.jpg")
new6 = Product.create(name: "The Low-Rise Perfect Vintage Straight Jean in Lunar Wash", gender: "womens", category: "new", price: 128.00, description: "The cut: We reworked our best-selling straight momjeans with a slouchy low rise that sits on the hips (without flashing your undies). The fabric: Premium denim that combines the holds-you-in structure of rigid with a touch of stretch for day-one comfort.")
new6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new6_1.jpg"), filename: "new6_1.jpg")
new6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new6_2.jpg"), filename: "new6_2.jpg")
new7 = Product.create(name: "Breezewoven Beachside Shirttail Top", gender: "womens", category: "new", price: 69.50, description: "Our safari-inspired Beachside button-up now has a longer-in-back shirttail hem (plus the same patch pockets). Ready to pair with the matching pants, it comes in our airy (and sustainable) Breezewoven basketweave linen blend.")
new7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new7_1.jpg"), filename: "new7_1.jpg")
new7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new7_2.jpg"), filename: "new7_2.jpg")
new8 = Product.create(name: "Breezewoven Larsen Blazer", gender: "womens", category: "new", price: 148.00, description: "Now in our airy Breezewoven basketweave linen blend, our fave just-a-touch oversized blazer makes you look both professional and laid-back at the same time (the vibe: you're not a regular boss, you're a cool boss). Plus, it's got two pockets on the outside and one on the inside so you can go hands-free any time you need to.")
new8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new8_1.jpg"), filename: "new8_1.jpg")
new8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new8_2.jpg"), filename: "new8_2.jpg")
new9 = Product.create(name: "Short-Brimmed Bucket Hat", gender: "womens", category: "new", price: 29.50, description: "Made of lightweight cotton canvas, this bucket style channels '90s skater vibes while keeping the sun out of your eyes.")
new9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new9_1.jpg"), filename: "new9_1.jpg")
new9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new9_2.jpg"), filename: "new9_2.jpg")
new10 = Product.create(name: "MWL Towel Terry Sweatshirt Bralette", gender: "womens", category: "new", price: 48.00, description: "The fabric: loop-y, lightweight towel terrycloth. The fit: inspired by old-school athletic gear, this square-neck bralette top has a comfy elastic underband. The (three-piece) set: wear it with the matching colorblock cardigan and shorts for a varsity vibe.")
new10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new10_1.jpg"), filename: "new10_1.jpg")
new10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new10_2.jpg"), filename: "new10_2.jpg")
new11 = Product.create(name: "Breezewoven Linen-Blend Tank Jumpsuit", gender: "womens", category: "new", price: 118.00, description: "Made of our new Breezewoven basketweave linen blend, this easy-on-the-body jumpsuit has tapered legs, button straps and, best of all, pockets. Wear it solo or layer it over a tee—there are so many options with this one.")
new11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new11_1.jpg"), filename: "new11_1.jpg")
new11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new11_2.jpg"), filename: "new11_2.jpg")
new12 = Product.create(name: "The Medium Transport Tote: Woven Leather Edition", gender: "womens", category: "new", price: 188.00, description: "What goes into this supersoft and slouchy version of our Medium Transport Tote? Here it is by the numbers: 100+ of pieces of fine leather are woven together by hand to make the body. 2 ways to carry: with the top handles or the detachable shoulder strap. 1 interior side zip pocket to keep your keys, phone and wallet at the ready. 24: the number of hours in a day that this bag looks cool.")
new12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new12_1.jpg"), filename: "new12_1.jpg")
new12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new12_2.jpg"), filename: "new12_2.jpg")
new13 = Product.create(name: "Linen-Blend Side-Button Midi Skirt", gender: "womens", category: "new", price: 89.50, description: "Made of an airy (and eco-friendly) linen blend, this pull-on midi skirt has buttons down the side so you can show a little leg. Add the matching top for an effortless summer set.")
new13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new13_1.jpg"), filename: "new13_1.jpg")
new13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/new13_2.jpg"), filename: "new13_2.jpg")

denim1 = Product.create(name: "11 inch High-Rise Flare Jeans in Wrenford Wash", gender: "womens", category: "denim", price: 128.00, description: "The cut: Complete with the holds-you-in sorcery of our Magic Pockets® in front, these '70s-inspired high-rise jeans have a slim fit through the hip and thigh before flaring at the knee. The fabric: Premium vintage-y stretch denim that hugs the body and bounces back like a pro (aka no 3pm bagginess).")
denim1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim1_1.jpg"), filename: "denim1_1.jpg")
denim1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim1_2.jpg"), filename: "denim1_2.jpg")
denim2 = Product.create(name: "The Plus High-Rise Slim Boyjean in Prentice Wash: Ripped Edition", gender: "womens", category: "denim", price: 138.00, description: "The cut: Easy in the (high) waist, our signature boyfriend fit has a slim-but-still-relaxed leg (think a vintage men's jean cut for you). The fabric: Our best-selling Heritage Stretch organic cotton denim has an old-school look and a touch of give for a perfectly broken-in feel.")
denim2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim2_1.jpg"), filename: "denim2_1.jpg")
denim2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim2_2.jpg"), filename: "denim2_2.jpg")
denim3 = Product.create(name: "High-Rise Slim Straight Jeans in Stillwood Wash: Slit-Hem Edition", gender: "womens", category: "denim", price: 98.00, description: "The cut: Complete with the holds-you-in sorcery of our Magic Pockets® in front, these high-rise stovepipe jeans have slim straight legs with slits in the hems to show off your shoes. The fabric: Supersoft (and eco-friendly) denim with tons of comfy stretch.")
denim3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim3_1.jpg"), filename: "denim3_1.jpg")
denim3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim3_2.jpg"), filename: "denim3_2.jpg")
denim4 = Product.create(name: "Curvy High-Rise Skinny Jeans in Pure White", gender: "womens", category: "denim", price: 128.00, description: "The cut: Designed for an hourglass shape (see: narrower waist with a contoured band, a longer rise and a little extra room at the hips and thighs), these skinny jeans are lean and legs-for-days sexy. The fabric: Premium white denim with zero show-through and tons of holds-you-in stretch.")
denim4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim4_1.jpg"), filename: "denim4_1.jpg")
denim4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim4_2.jpg"), filename: "denim4_2.jpg")
denim5 = Product.create(name: "The Perfect Vintage Wide-Leg Crop Jean in Montclare Wash: TENCEL™ Denim Edition", gender: "womens", category: "denim", price: 128.00, description: "The cut: The latest addition to our Perfect Vintage fam, these cropped jeans combine our classic high fitted waist with slouchy wide legs. The fabric: Blended with sustainable (and soft-to-the-touch) TENCEL™ lyocell, our best-selling Heritage Stretch denim has an old-school look and a touch of give for a perfectly broken-in feel.")
denim5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim5_1.jpg"), filename: "denim5_1.jpg")
denim5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim5_2.jpg"), filename: "denim5_2.jpg")
denim6 = Product.create(name: "The Perfect Vintage Wide-Leg Full-Length Jean in Elmont Wash", gender: "womens", category: "denim", price: 138.00, description: "The cut: The latest addition to our Perfect Vintage fam, these full-length jeans combine our classic high fitted waist with slouchy wide legs. The fabric: Our best-selling Heritage Stretch denim has an old-school look and a touch of give for a perfectly broken-in feel.")
denim6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim6_1.jpg"), filename: "denim6_1.jpg")
denim6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim6_2.jpg"), filename: "denim6_2.jpg")
denim7 = Product.create(name: "The Perfect Vintage Jean: Botanical Dye Edition", gender: "womens", category: "denim", price: 138.00, description: "With their waist-accentuating high rise and tapered legs, these are 'mom jeans'...if your mom was a '90s supermodel. Naturally dyed using barks, roots, berries and other botanicals, this special pair is made of our best-selling Heritage Stretch denim that has an old-school look and a touch of give for a perfectly broken-in feel.")
denim7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim7_1.jpg"), filename: "denim7_1.jpg")
denim7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim7_2.jpg"), filename: "denim7_2.jpg")
denim8 = Product.create(name: "Denim Oversized Carpenter Overalls in Bretton Wash", gender: "womens", category: "denim", price: 158.00, description: "The cut: Designed to wear with tiny tops, these oversized overalls are superrelaxed with workwear details like a hammer loop and those extra side pockets (for a measuring tape, nails or, you know, a phone). The fabric: Old-school 100 percent cotton denim with zero stretch.")
denim8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim8_1.jpg"), filename: "denim8_1.jpg")
denim8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim8_2.jpg"), filename: "denim8_2.jpg")
denim9 = Product.create(name: "The Girljean in Berryton Wash: Distressed Edition", gender: "womens", category: "denim", price: 88.00, description: "The cut: Comfy and cool, our high-rise girlfriend jeans have a slim-meets-relaxed leg (perfect for when you are branching out from skinnies). The fabric: Our best-selling Heritage Stretch denim has an old-school look and a touch of give for a perfectly broken-in feel.")
denim9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim9_1.jpg"), filename: "denim9_1.jpg")
denim9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim9_2.jpg"), filename: "denim9_2.jpg")
denim10 = Product.create(name: "The Plus Curvy Perfect Vintage Wide-Leg Jean in Edmunds Wash", gender: "womens", category: "denim", price: 128.00, description: "The cut: Reengineered for those with an hourglass shape, our wide-legged '90s supermodel momjeans have a narrower waist with a contoured band, a longer rise (for a rounder booty) and a little extra room at the hips and thighs. The fabric: Blended with recycled cotton, this premium denim combines the holds-you-in structure of rigid with a touch of comfy stretch.")
denim10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim10_1.jpg"), filename: "denim10_1.jpg")
denim10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim10_2.jpg"), filename: "denim10_2.jpg")
denim11 = Product.create(name: "Balloon Jeans in Tile White: Button-Front Edition", gender: "womens", category: "denim", price: 128.00, description: "The cut: Updated with a high button-front waist, these street style-inspired jeans are fitted at the waist with curved '80s 'balloon' legs. The fabric: Premium 100 percent cotton white denim with old-school character, no stretch and zero show-through.")
denim11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim11_1.jpg"), filename: "denim11_1.jpg")
denim11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim11_2.jpg"), filename: "denim11_2.jpg")
denim12 = Product.create(name: "Closed® Edison Jeans in Mid Blue Vintage Wash", gender: "womens", category: "denim", price: 5.00, description: "Founded in 1978, Closed specializes in sustainable clothing with a distinctly European vibe. Made in Italy of 100 percent organic cotton denim, these high-rise jeans have a slouchy straight leg.")
denim12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim12_1.jpg"), filename: "denim12_1.jpg")
denim12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim12_2.jpg"), filename: "denim12_2.jpg")
denim13 = Product.create(name: "The Momjean in Yarn-Dyed Denim", gender: "womens", category: "denim", price: 80.00, description: "The cut: The ultimate momjean, this superhigh-rise fit has perfectly tapered legs. The fabric: Woven from specially dyed threads for dimensional color, this structured denim has just a touch of comfy stretch.")
denim13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim13_1.jpg"), filename: "denim13_1.jpg")
denim13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/denim13_2.jpg"), filename: "denim13_2.jpg")

clothing1 = Product.create(name: "Whisper Cotton Rib-Crewneck Tee", gender: "womens", category: "clothing", price: 19.50, description: "Light, airy and live-in-it soft, our perfectly draped best-selling tee has a ribbed crewneck with an authentically vintage feel—one to tell your friends about, in other words.")
clothing1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing1_1.jpg"), filename: "clothing1_1.jpg")
clothing1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing1_2.jpg"), filename: "clothing1_2.jpg")
clothing2 = Product.create(name: "Puff-Sleeve Scoop Midi Dress", gender: "womens", category: "clothing", price: 138.00, description: "Made of sustainable Lenzing™ Ecovero™ viscose, this puff-sleeve midi dress has a scoop neck, a fitted bodice and a full swingy skirt. Coming in solid black, it's a dreamy style you can also wear to work.")
clothing2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing2_1.jpg"), filename: "clothing2_1.jpg")
clothing2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing2_2.jpg"), filename: "clothing2_2.jpg")
clothing3 = Product.create(name: "The Perfect Vintage Straight Workwear Pant", gender: "womens", category: "clothing", price: 88.00, description: "The cut: Complete with workwear-inspired details like patch pockets, these utility pants come in the same high-rise straight-legged fit as our best-selling '90s supermodel jeans. The fabric: Garment-dyed for dimensional color, this sturdy herringbone fabric has a touch of stretch for day-one comfort.")
clothing3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing3_1.jpg"), filename: "clothing3_1.jpg")
clothing3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing3_2.jpg"), filename: "clothing3_2.jpg")
clothing4 = Product.create(name: "Marianna Puff-Sleeve Midi Dress in Dream-On Daisies", gender: "womens", category: "clothing", price: 135.00, description: "Made of breezy cotton in a playful daisy print, this midi dress has lots of details to love: a faux-wrap bodice, raglan puff sleeves and a roomy skirt with delicate pintucks. A pretty, no-fuss style.")
clothing4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing4_1.jpg"), filename: "clothing4_1.jpg")
clothing4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing4_2.jpg"), filename: "clothing4_2.jpg")
clothing5 = Product.create(name: "Eyelet-Trim Tiered Mini Dress in Piccola Floral", gender: "womens", category: "clothing", price: 138.00, description: "Crafted of breezy floral cotton, this tiered mini dress has a beautiful embroidered eyelet V-neckline and puff sleeves with elasticized ruffles. Cute and easy with a floaty A-line shape, it's perfect for any warm-weather gathering.")
clothing5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing5_1.jpg"), filename: "clothing5_1.jpg")
clothing5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing5_2.jpg"), filename: "clothing5_2.jpg")
clothing6 = Product.create(name: "Breezewoven Pull-On High-Rise Straight Pants", gender: "womens", category: "clothing", price: 78.00, description: "The cut: A pull-on pair that can go to the office, these straight-leg pants have subtle pintucks for a pre-creased look (and look so polished with the matching blazer or top). The fabric: Our airy Breezewoven basketweave is a summer-friendly blend of linen and sustainable Lenzing™ Ecovero™ viscose.")
clothing6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing6_1.jpg"), filename: "clothing6_1.jpg")
clothing6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing6_2.jpg"), filename: "clothing6_2.jpg")
clothing7 = Product.create(name: "Linen-Blend Curved-Hem Shorts in Stripe", gender: "womens", category: "clothing", price: 64.50, description: "The cut: with their high elastic waist and curved hems, these shorts are as breezy, cool and wear-anywhere versatile as a skirt. The fabric: an airy linen blended with sustainable Lenzing™ Ecovero™ viscose.")
clothing7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing7_1.jpg"), filename: "clothing7_1.jpg")
clothing7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing7_2.jpg"), filename: "clothing7_2.jpg")
clothing8 = Product.create(name: "Ribbed Button-Front Crop Tank", gender: "womens", category: "clothing", price: 48.00, description: "Made of body-hugging ribbed fabric, this perfectly cropped button-front tank has a square neckline and bra-friendly wide straps. Very '90s vibes with baggy jeans.")
clothing8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing8_1.jpg"), filename: "clothing8_1.jpg")
clothing8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing8_2.jpg"), filename: "clothing8_2.jpg")
clothing9 = Product.create(name: "Rujuta Sheth Tie-Front Maxi Dress", gender: "womens", category: "clothing", price: 268.00, description: "Focusing on sustainability and longevity, NYC-based Rujuta Sheth designs modern clothes crafted with traditional techniques inspired by her childhood spent in India. Made of cotton, this flowy tiered maxi dress has adjustable ties on the bodice and a drawstring waist.")
clothing9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing9_1.jpg"), filename: "clothing9_1.jpg")
clothing9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing9_2.jpg"), filename: "clothing9_2.jpg")
clothing10 = Product.create(name: "Seersucker Sophia Peplum Tank in Rainbow Gingham Check", gender: "womens", category: "clothing", price: 75.00, description: "Coming in a colorful seersucker cotton, this cropped peplum tank is the newest addition to our Sophia fam (it has the same shirred elastic waist that looks good on everyone). With wide bra-friendly straps and a tie in back, it's an instant summer fave.")
clothing10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing10_1.jpg"), filename: "clothing10_1.jpg")
clothing10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing10_2.jpg"), filename: "clothing10_2.jpg")
clothing11 = Product.create(name: "Ruched Keyhole Tiered Midi Dress", gender: "womens", category: "clothing", price: 178.00, description: "Smocked in back for the perfect fit, this tiered midi dress has a subtle keyhole cutout in front below a ruched bodice with adjustable bead-trimmed ties. Pair it with strappy sandals for alllll those wedding weekends you have coming up.")
clothing11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing11_1.jpg"), filename: "clothing11_1.jpg")
clothing11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing11_2.jpg"), filename: "clothing11_2.jpg")
clothing12 = Product.create(name: "Lightestspun Tie-Front Cover-Up Crop Shirt", gender: "womens", category: "clothing", price: 59.50, description: "Made of a featherweight version of our supersoft Lightspun double-layered cotton gauze, this cropped camp shirt has long ties in front that can be knotted closed or left undone. Layer it over a bikini as a cover-up or wear it as a set with the matching shorts.")
clothing12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing12_1.jpg"), filename: "clothing12_1.jpg")
clothing12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing12_2.jpg"), filename: "clothing12_2.jpg")
clothing13 = Product.create(name: "Lightspun Westing Shirt in Stripe", gender: "womens", category: "clothing", price: 68.00, description: "Made of our supersoft and airy Lightspun double-layered cotton gauze, this striped popover top has a relaxed, laid-back vibe. Cuffed sleeves and shirring along the back give it that perfect just-off-the-body fit.")
clothing13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing13_1.jpg"), filename: "clothing13_1.jpg")
clothing13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/clothing13_2.jpg"), filename: "clothing13_2.jpg")

shoes1 = Product.create(name: "The Charley Double-Strap Slide Sandal", gender: "womens", category: "shoes", price: 110.00, description: "Comfy and slip-on easy, these leather slides have sleek double straps and a flexible molded footbed complete with MWL Cloudlift Lite padding that feels like walking on a...well, you know.")
shoes1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes1_1.jpg"), filename: "shoes1_1.jpg")
shoes1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes1_2.jpg"), filename: "shoes1_2.jpg")
shoes2 = Product.create(name: "Court Sneakers in White Leather", gender: "womens", category: "shoes", price: 98.00, description: "Our newest sneakers have a minimalist shape meant to go with everything. Complete with our supercushy, ultra-supportive MWL Cloudlift insoles, they're also as eco-friendly as possible—reclaimed from what would otherwise be waste, the leather comes from a Gold-certified tannery and the chunky outsoles are made of recycled rubber and rice husks.")
shoes2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes2_1.jpg"), filename: "shoes2_1.jpg")
shoes2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes2_2.jpg"), filename: "shoes2_2.jpg")
shoes3 = Product.create(name: "The Walker Slide Sandal", gender: "womens", category: "shoes", price: 78.00, description: "Made with comfort in mind (there's a reason we call it the 'Walker'), these slide sandals have wavy straps with a touch of puff.")
shoes3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes3_1.jpg"), filename: "shoes3_1.jpg")
shoes3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes3_2.jpg"), filename: "shoes3_2.jpg")
shoes4 = Product.create(name: "The Corinne Lugsole Loafer", gender: "womens", category: "shoes", price: 158.00, description: "A classic penny loafer with a '90s-inspired chunky lug sole, this pair is made from ISA™ LITE (Low Impact To the Environment) leather that uses less energy and water than the standard tanning process. An alternative to booties to go with your midi skirts and wide-leg pants.")
shoes4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes4_1.jpg"), filename: "shoes4_1.jpg")
shoes4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes4_2.jpg"), filename: "shoes4_2.jpg")
shoes5 = Product.create(name: "The Kiera Lugsole Sandal", gender: "womens", category: "shoes", price: 148.00, description: "We revamped our best-selling sandals with a walkable stacked heel and a chunky lugsole. Made of responsibly sourced leather, they have our MWL Cloudlift padding that feels like walking on a...well, you know.")
shoes5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes5_1.jpg"), filename: "shoes5_1.jpg")
shoes5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes5_2.jpg"), filename: "shoes5_2.jpg")
shoes6 = Product.create(name: "The Addie Sandal", gender: "womens", category: "shoes", price: 118.00, description: "Made of oiled vachetta leather, these strappy sandals have a suede-lined molded footbed and a flexible sawtooth sole (yeah, that's really what it's called). Flatform vibes mean you'll be walking a little taller on your next iced coffee run.")
shoes6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes6_1.jpg"), filename: "shoes6_1.jpg")
shoes6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes6_2.jpg"), filename: "shoes6_2.jpg")
shoes7 = Product.create(name: "The Hallie Espadrille Sandal in Leather", gender: "womens", category: "shoes", price: 98.00, description: "Combining sporty Velcro straps with classic jute soles, these supercute (and supersecure) sandals come in leather from a Gold-certified tannery—and some of it was even repurposed from scraps (!). And, psst, we always read your reviews, so this year we made our espadrilles even cushier (our MWL Cloudlift Lite padding feels like walking on a...well, you know).")
shoes7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes7_1.jpg"), filename: "shoes7_1.jpg")
shoes7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes7_2.jpg"), filename: "shoes7_2.jpg")
shoes8 = Product.create(name: "Veja™ Leather V-12 Lace-Up Sneakers in White and Natural", gender: "womens", category: "shoes", price: 150.00, description: "Founded in Paris, Veja makes eco-friendly sneakers that don't look eco-friendly (aka, they're feel-good shoes without the crunch factor). These retro leather low-tops are crafted in Brazil from sustainable materials, including recycled polyester lining, plus, the soles are of wild rubber from the Amazonian rain forest.")
shoes8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes8_1.jpg"), filename: "shoes8_1.jpg")
shoes8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes8_2.jpg"), filename: "shoes8_2.jpg")
shoes9 = Product.create(name: "The Evelina Espadrille in (Re)sourced Canvas", gender: "womens", category: "shoes", price: 128.00, description: "Made of (Re)sourced recycled canvas with leather trim, these classic espadrille sandals have an easy ankle strap and a walkable low wedge heel (that looks so good with a midi skirt). And, cushiness alert: our MWL Cloudlift Lite padding feels like walking on a...well, you know.")
shoes9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes9_1.jpg"), filename: "shoes9_1.jpg")
shoes9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes9_2.jpg"), filename: "shoes9_2.jpg")
shoes10 = Product.create(name: "The Cassady Mule in Woven Leather", gender: "womens", category: "shoes", price: 118.00, description: "Woven from Gold-certified sustainable leather, these multicolored low-heeled mules have wide straps and stylish square toes for a low-key '90s vibe. Very necessary for the day-to-night thing (our cushy MWL Cloudlift Lite padding feels like walking on a...well, you know).")
shoes10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes10_1.jpg"), filename: "shoes10_1.jpg")
shoes10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes10_2.jpg"), filename: "shoes10_2.jpg")
shoes11 = Product.create(name: "The Julie Espadrille Sandal", gender: "womens", category: "shoes", price: 110.00, description: "A fresh take on classic espadrilles, these slingback sandals have chunky jute soles and sturdy (Re)sourced recycled canvas straps bound in sustainable leather. And, cushiness alert: our MWL Cloudlift Lite padding feels like walking on a...well, you know...so you'll want to wear them indoors and out.")
shoes11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes11_1.jpg"), filename: "shoes11_1.jpg")
shoes11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes11_2.jpg"), filename: "shoes11_2.jpg")
shoes12 = Product.create(name: "On Roger Advantage Sneakers", gender: "womens", category: "shoes", price: 140.00, description: "Founded in Zurich by three buddies passionate about athletics, On shoes combine sleek design with state-of-the-art tech. Co-Created with tennis legend Roger Federer, these vegan leather court sneakers have comfy CloudTec® soles.")
shoes12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes12_1.jpg"), filename: "shoes12_1.jpg")
shoes12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes12_2.jpg"), filename: "shoes12_2.jpg")
shoes13 = Product.create(name: "The Jayna Braided Slide Sandal", gender: "womens", category: "shoes", price: 98.00, description: "Artfully braided from buttery soft leather, these slip-on sandals are a luxe update to pool slides. And, cushiness alert: our MWL Cloudlift Lite padding feels like walking on a...well, you know.")
shoes13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes13_1.jpg"), filename: "shoes13_1.jpg")
shoes13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/shoes13_2.jpg"), filename: "shoes13_2.jpg")

accessories1 = Product.create(name: "The Medium Transport Tote", gender: "womens", category: "accessories", price: 168.00, description: "What goes into our Medium Transport Tote? Here it is by the numbers: 2 pieces of fine leather are used for the body. 2 ways to carry: with the top handles or the detachable shoulder strap. 1 exterior pocket for those things you gotta grab fast. 1 interior side zip pocket to keep your keys, phone and wallet at the ready. 24: the number of hours in a day that this bag looks cool. How often you'll reach for it? 500 gazillion times.")
accessories1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories1_1.jpg"), filename: "accessories1_1.jpg")
accessories1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories1_2.jpg"), filename: "accessories1_2.jpg")
accessories2 = Product.create(name: "Organic Cotton Broken-In Baseball Cap", gender: "womens", category: "accessories", price: 29.50, description: "Specially washed for a perfectly broken-in feel, this timeless baseball cap has an adjustable leather back strap. Throw it on, look instantly cooler.")
accessories2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories2_1.jpg"), filename: "accessories2_1.jpg")
accessories2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories2_2.jpg"), filename: "accessories2_2.jpg")
accessories3 = Product.create(name: "Enamel Strawberry Huggie Hoop Earrings", gender: "womens", category: "accessories", price: 26.00, description: "Go fruit forward with these enamel strawberry charms hung from gold-plated recycled brass huggie hoops. An unexpectedly sweet addition to any earrings set.")
accessories3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories3_1.jpg"), filename: "accessories3_1.jpg")
accessories3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories3_2.jpg"), filename: "accessories3_2.jpg")
accessories4 = Product.create(name: "Silk Tie-Dye Bandana", gender: "womens", category: "accessories", price: 12.50, description: "Edged in delicate eyelet details, this tie-dyed-by-hand silk bandana is a chilled-out accessory with endless possibilities: Wear it as a kerchief, tie it onto a tote, wrap it around your wrist...you can't go wrong with this one.")
accessories4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories4_1.jpg"), filename: "accessories4_1.jpg")
accessories4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories4_2.jpg"), filename: "accessories4_2.jpg")
accessories5 = Product.create(name: "Mushroom Paperclip Chain Anklet", gender: "womens", category: "accessories", price: 24.00, description: "Lean into the cottagecore thing with this gold-plated brass anklet with the teeniest lil mushroom charm. (Shoes? Totally optional.)")
accessories5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories5_1.jpg"), filename: "accessories5_1.jpg")
accessories5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories5_2.jpg"), filename: "accessories5_2.jpg")
accessories6 = Product.create(name: "Woven Sash Belt", gender: "womens", category: "accessories", price: 36.00, description: "Soft, light and intricately woven, this versatile sash belt adds a touch of texture to any look. The styling options are endless: tie it at the waist, knot it at the hip, wear it however you like.")
accessories6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories6_1.jpg"), filename: "accessories6_1.jpg")
accessories6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories6_2.jpg"), filename: "accessories6_2.jpg")
accessories7 = Product.create(name: "The (Re)sourced Tote Bag", gender: "womens", category: "accessories", price: 98.00, description: "Made of soft and sturdy (Re)sourced recycled material, this multipurpose bag has tons of pockets inside and out and a padded laptop compartment. Use it for a picnic in the park, an outdoor workout or just to haul around your daily necessities (it's very kid- and dog-friendly).")
accessories7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories7_1.jpg"), filename: "accessories7_1.jpg")
accessories7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories7_2.jpg"), filename: "accessories7_2.jpg")
accessories8 = Product.create(name: "Medium Perfect Leather Belt", gender: "womens", category: "accessories", price: 48.00, description: "It doesn't get more timeless than this lovingly worn-in belt—you'll have it in your accessories repertoire for years to come. Please note: Size down if you want to wear it at the waist (like, say, to cinch your favorite dress).")
accessories8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories8_1.jpg"), filename: "accessories8_1.jpg")
accessories8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories8_2.jpg"), filename: "accessories8_2.jpg")
accessories9 = Product.create(name: "Three-Pack Assorted Adjustable Face Masks", gender: "womens", category: "accessories", price: 24.00, description: "Designed with comfort in mind, our non-medical cotton face masks have secure adjustable elastic ear straps and a three-layered construction that includes a filter. Bonus: This multi-pack comes in our favorite prints of the season.")
accessories9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories9_1.jpg"), filename: "accessories9_1.jpg")
accessories9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories9_2.jpg"), filename: "accessories9_2.jpg")
accessories10 = Product.create(name: "Herringbone Chain Necklace", gender: "womens", category: "accessories", price: 34.00, description: "Oh, nothing to see here—just the shiniest, prettiest necklace we've ever laid eyes upon. Made of gold-plated brass, this chain is perfect for layering.")
accessories10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories10_1.jpg"), filename: "accessories10_1.jpg")
accessories10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories10_2.jpg"), filename: "accessories10_2.jpg")
accessories11 = Product.create(name: "Packable Braided Straw Hat", gender: "womens", category: "accessories", price: 39.50, description: "Go ahead and throw this braided straw hat into your bag, it's perfectly unstructured so you don't have to be too careful when packing it up.")
accessories11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories11_1.jpg"), filename: "accessories11_1.jpg")
accessories11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories11_2.jpg"), filename: "accessories11_2.jpg")
accessories12 = Product.create(name: "The Large Transport Camera Bag: Bandana Embossed Edition", gender: "womens", category: "accessories", price: 168.00, description: "Our best-selling large camera bag gets a spring-friendly makeover in luxe vachetta leather embossed with bandana-inspired flowers. Picture-perfectly sized to hold a book, water bottle and wallet, it has a hidden pocket in front (and one inside for your ID).")
accessories12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories12_1.jpg"), filename: "accessories12_1.jpg")
accessories12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories12_2.jpg"), filename: "accessories12_2.jpg")
accessories13 = Product.create(name: "Paperclip Chain Necklace", gender: "womens", category: "accessories", price: 38.00, description: "In vintage-y gold plated brass, this adjustable open-chain necklace is perfect for layering with your faves—or wear it solo as a delicate statement piece.")
accessories13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories13_1.jpg"), filename: "accessories13_1.jpg")
accessories13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/accessories13_2.jpg"), filename: "accessories13_2.jpg")

brands1 = Product.create(name: "WVN Becca Dress", gender: "womens", category: "brands", price: 254.00, description: "Founded by Kate Fisher in 2021, this brand designs sustainably chic clothing for women who are about the world and want to look cute too. With a flowy asymmetrical tiered skirt, the Becca Dress is both refined and relaxed. This dress will grace your natural silhouette with fitted quarter sleeves and a belted waist. Finished with a clean V-notched collar and crafted from organic cotton, this is an unforgettable icon.")
brands1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands1_1.jpg"), filename: "brands1_1.jpg")
brands1.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands1_2.jpg"), filename: "brands1_2.jpg")
brands2 = Product.create(name: "WVN Sienna Blouse", gender: "womens", category: "brands", price: 80.00, description: "Founded by Kate Fisher in 2021, this brand designs sustainably chic clothing for women who are about the world and want to look cute too. A sustainable take on every woman's most-loved blouse. Constructed from lightweight organic cotton poplin, the Sienna is easy-fitting with just the right amount of structure. With a charming puffed sleeve silhouette, this blouse embodies everything classic.")
brands2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands2_1.jpg"), filename: "brands2_1.jpg")
brands2.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands2_2.jpg"), filename: "brands2_2.jpg")
brands3 = Product.create(name: "Birkenstock® Arizona EVA Sandals", gender: "womens", category: "brands", price: 44.95, description: "For over 200 years, this quintessential European sandal maker has been without an equal when it comes to übercomfy (and cool) styles you can walk in for hours. These classic double-strap sandals are made in Germany from light-as-air EVA (ethylene vinyl acetate), making them flexible, washable and incredibly easy on the feet.")
brands3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands3_1.jpg"), filename: "brands3_1.jpg")
brands3.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands3_2.jpg"), filename: "brands3_2.jpg")
brands4 = Product.create(name: "Anchal® Organic Cotton Array Throw Pillow", gender: "womens", category: "brands", price: 94.00, description: "Sisters Colleen and Maggie Clines founded this textile brand, which employs and empowers women artisans in India. Crafted from certified organic cotton, this throw pillow is hand-stitched with a cool art deco design.")
brands4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands4_1.jpg"), filename: "brands4_1.jpg")
brands4.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands4_2.jpg"), filename: "brands4_2.jpg")
brands5 = Product.create(name: "Teva® Original Universal Sandals", gender: "womens", category: "brands", price: 55.00, description: "First dreamt up by a resourceful Grand Canyon river guide who'd lost one-too-many flip-flops floating downstream, Teva has been outfitting the feet of adventure-seekers since 1984. Made of recycled poly webbing, these ultra-versatile sandals look great with everything from dresses to jeans to swimsuits.")
brands5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands5_1.jpg"), filename: "brands5_1.jpg")
brands5.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands5_2.jpg"), filename: "brands5_2.jpg")
brands6 = Product.create(name: "Madewell x LAUDE the Label Thea Romper in Sea Mist", gender: "womens", category: "brands", price: 168.00, description: "Combining her passion for social justice and experience in the fashion industry, LAUDE the Label (formerly known as Tribe Alive) founder Carly Burson provides meaningful employment to female artisans around the world. This exclusive one-piece romper has a shirred elastic neckline for the comfiest feel.")
brands6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands6_1.jpg"), filename: "brands6_1.jpg")
brands6.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands6_2.jpg"), filename: "brands6_2.jpg")
brands7 = Product.create(name: "Fetchwell x Lisa Congdon Love To All Pride Perfect Vintage Tee", gender: "womens", category: "brands", price: 49.50, description: "Love to all (!)—show your pride with an exclusive graphic created by illustrator Lisa Congdon. 50 percent of the purchase price of this Perfect Vintage Tee will go to the ACLU and its mission to maintain and advance civil liberties for all.")
brands7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands7_1.jpg"), filename: "brands7_1.jpg")
brands7.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands7_2.jpg"), filename: "brands7_2.jpg")
brands8 = Product.create(name: "Odette New York® Beau Hoop Earrings", gender: "womens", category: "brands", price: 120.00, description: "Launched in 2006, Odette New York is a Brooklyn-based jewelry studio known for its signature sculptural pieces. Made in NYC, these front-facing hoops are the kind of earrings you'll want to wear every day.")
brands8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands8_1.jpg"), filename: "brands8_1.jpg")
brands8.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands8_2.jpg"), filename: "brands8_2.jpg")
brands9 = Product.create(name: "LIVELY The All-Day Short Sleeve Shirt", gender: "womens", category: "brands", price: 55.00, description: "The ladies-first innovators at LIVELY have created what they call 'leisurée,' aka comfortable, sexy underthings and suits made from only the best materials. This chic, all-day lounge shirt elevates your casual style with ease. Its classic silhouette has a tailored fit with a breezy fit.")
brands9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands9_1.jpg"), filename: "brands9_1.jpg")
brands9.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands9_2.jpg"), filename: "brands9_2.jpg")
brands10 = Product.create(name: "tailored union Andy Socks", gender: "womens", category: "brands", price: 16.00, description: "Tailored Union is all about giving some meaning to your daily rituals with their limited-edition runs of art-inspired socks. These short trouser ankles featuring a double cylinder knit are the perfect add on to any outfit. These socks are made with our premium cotton and are an ultra soft and stylish sock choice.")
brands10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands10_1.jpg"), filename: "brands10_1.jpg")
brands10.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands10_2.jpg"), filename: "brands10_2.jpg")
brands11 = Product.create(name: "Richer Poorer Recycled Crop Tee in Tie-Dye", gender: "womens", category: "brands", price: 38.00, description: "Based in California, Tim Morse and Iva Pawling of Richer Poorer began making socks and expanded into all kinds of laid-back essentials. Made of 40 percent recycled poly, this artfully tie-dyed T-shirt has dropped shoulders and a relaxed, cropped fit.")
brands11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands11_1.jpg"), filename: "brands11_1.jpg")
brands11.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands11_2.jpg"), filename: "brands11_2.jpg")
brands12 = Product.create(name: "Esselle Cream Scrunchies Bundle", gender: "womens", category: "brands", price: 25.00, description: "Based in San Francisco, the all-lady crew behind Esselle is serious about thoughtfully designed home accessories. This darling bundle comes with three scrunchies in different fabric textures and colors! Our darling neutral bundle comes with 3 scrunchies in different fabric textures and colors!")
brands12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands12_1.jpg"), filename: "brands12_1.jpg")
brands12.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands12_2.jpg"), filename: "brands12_2.jpg")
brands13 = Product.create(name: "Slowtide Guild 2-Piece Towel Bundle", gender: "womens", category: "brands", price: 99.95, description: "Founded in 2015 by a trio of surf buddies, Slowtide makes have-to-them home and beach accessories (dream job alert: they test them out near their California and Hawaii HQs). Crafted from sustainably sourced cotton, Slowtide Bath Towels are absorbent, plush and stylish, giving you the ultimate drying experience. Guild features a loose textured waffle fabric that is lightweight and quick-drying. Three-dimensional texture gives more surface to the towel, allowing for better drying.")
brands13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands13_1.jpg"), filename: "brands13_1.jpg")
brands13.photos.attach(io: open("https://kzxt-seed.s3.us-west-1.amazonaws.com/Phillip/fetchwell_jpeg/brands13_2.jpg"), filename: "brands13_2.jpg")

CartItem.create(quantity: 2, size: "M", user_id: demouser.id, product_id: new1.id)
CartItem.create(quantity: 1, size: "S", user_id: demouser.id, product_id: new2.id)
CartItem.create(quantity: 3, size: "S", user_id: demouser.id, product_id: new4.id)
CartItem.create(quantity: 5, size: "M", user_id: demouser.id, product_id: denim3.id)

listProducts = []
listProducts.push(new1, new2, new3, new4, new5, new6, new7, new8, new9, new10, new11, new12, new13)
listProducts.push(denim1, denim2, denim3, denim4, denim5, denim6, denim7, denim8, denim9, denim10, denim11, denim12, denim13)
listProducts.push(clothing1, clothing2, clothing3, clothing4, clothing5, clothing6, clothing7, clothing8, clothing9, clothing10, clothing11, clothing12, clothing13)
listProducts.push(accessories1, accessories2, accessories3, accessories4, accessories5, accessories6, accessories7, accessories8, accessories9, accessories10, accessories11, accessories12, accessories13)
listProducts.push(brands1, brands2, brands3, brands4, brands5, brands6, brands7, brands8, brands9, brands10, brands11, brands12, brands13)
listProducts.push(shoes1, shoes2, shoes3, shoes4, shoes5, shoes6, shoes7, shoes8, shoes9, shoes10, shoes11, shoes12, shoes13)

listProducts.each do |item|
    Review.create(location: Faker::Address.city + ", " + Faker::Address.state_abbr, overall_fit: Faker::Number.between(from: 30, to: 70), rating: Faker::Number.between(from: 4, to: 5), author_id: user1.id, nickname: Faker::Name.first_name, product_id: item.id, summary: "I love it", description: "I have waited forever for this product it was well worth the wait. Looks super cute and you can match it with almost anything! The fit is a little loose/relaxed, but I'm pretty sure that's how it's supposed to be. Overall, well surpassed my expectations and would buy from here again.")
    Review.create(location: Faker::Address.city + ", " + Faker::Address.state_abbr, overall_fit: Faker::Number.between(from: 30, to: 70), rating: Faker::Number.between(from: 1, to: 2), author_id: user3.id, nickname: Faker::Name.first_name, product_id: item.id, summary: "Not so great", description: "I was very excited when I my order finally shipped (after two weeks) and arrived in the mail, but I am sad to say that I was very dissapointed when i opened it. The product did not look like in the description at all. Material was not so great and felt kind of 'cheap.' The fit was very loose despite what these other reviews say. I will be requesting a refund and will not be ordering from here again.")
    Review.create(location: Faker::Address.city + ", " + Faker::Address.state_abbr, overall_fit: Faker::Number.between(from: 30, to: 70), rating: Faker::Number.between(from: 4, to: 5), author_id: user2.id, nickname: Faker::Name.first_name, product_id: item.id, summary: "Good quality", description: "Finally found something that I can use wear everyday. The material is very good and it does not stain easily (for those moms out there). Yet, it's still very stylish without being too much 'out there.' It felt a little loose, but it didn't really bother me at all. I will probably buy from here again in the future.")
    Review.create(location: Faker::Address.city + ", " + Faker::Address.state_abbr, overall_fit: Faker::Number.between(from: 30, to: 70), rating: Faker::Number.between(from: 3, to: 4), author_id: user4.id, nickname: Faker::Name.first_name, product_id: item.id, summary: "Just average", description: "It looked very nice in the pictures, but when I got them the fit was a bit different than was specified. They still wore okay, but I wish it was a bit tighter. Be careful when washing these, as it will wear down the product. Make sure to use cold water and hang dry in the air.")
end


# Like.create(user_id: user1.id, review_id: review2.id)
# Like.create(user_id: user2.id, review_id: review3.id)
# Like.create(user_id: user3.id, review_id: review4.id)
# Like.create(user_id: user4.id, review_id: review5.id)
# Like.create(user_id: user5.id, review_id: review6.id)
# Like.create(user_id: user6.id, review_id: review7.id)
# Like.create(user_id: user7.id, review_id: review8.id)
# Like.create(user_id: user8.id, review_id: review9.id)
# Like.create(user_id: user9.id, review_id: review1.id)

# Like.create(user_id: user1.id, review_id: review3.id)
# Like.create(user_id: user2.id, review_id: review4.id)
# Like.create(user_id: user3.id, review_id: review5.id)
# Like.create(user_id: user4.id, review_id: review6.id)
# Like.create(user_id: user5.id, review_id: review7.id)
# Like.create(user_id: user6.id, review_id: review8.id)
# Like.create(user_id: user7.id, review_id: review9.id)
# Like.create(user_id: user8.id, review_id: review1.id)
# Like.create(user_id: user9.id, review_id: review2.id)

